CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'...EF.E.E.....E........E....E.....E.FE.......EE........FF..E.......E...........E...E.............E..\n======================================================================\nERROR: test11 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 78, in test11\n    self.assertEqual(patched_source(*input_11), original_source(*input_11))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test14 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 96, in test14\n    self.assertEqual(patched_source(*input_14), original_source(*input_14))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test16 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 108, in test16\n    self.assertEqual(patched_source(*input_16), original_source(*input_16))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test21 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 138, in test21\n    self.assertEqual(patched_source(*input_21), original_source(*input_21))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test3 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 30, in test3\n    self.assertEqual(patched_source(*input_3), original_source(*input_3))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test34 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 216, in test34\n    self.assertEqual(patched_source(*input_34), original_source(*input_34))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test4 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 36, in test4\n    self.assertEqual(patched_source(*input_4), original_source(*input_4))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test42 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 264, in test42\n    self.assertEqual(patched_source(*input_42), original_source(*input_42))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test5 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 42, in test5\n    self.assertEqual(patched_source(*input_5), original_source(*input_5))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test50 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 312, in test50\n    self.assertEqual(patched_source(*input_50), original_source(*input_50))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test62 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 384, in test62\n    self.assertEqual(patched_source(*input_62), original_source(*input_62))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test7 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 54, in test7\n    self.assertEqual(patched_source(*input_7), original_source(*input_7))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test80 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 492, in test80\n    self.assertEqual(patched_source(*input_80), original_source(*input_80))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test84 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 516, in test84\n    self.assertEqual(patched_source(*input_84), original_source(*input_84))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test97 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 594, in test97\n    self.assertEqual(patched_source(*input_97), original_source(*input_97))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nFAIL: test12 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 84, in test12\n    self.assertEqual(patched_source(*input_12), original_source(*input_12))\nAssertionError: Lists differ: [\'-1\'] != [12]\n\nFirst differing element 0:\n\'-1\'\n12\n\n- [\'-1\']\n+ [12]\n\n======================================================================\nFAIL: test41 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 258, in test41\n    self.assertEqual(patched_source(*input_41), original_source(*input_41))\nAssertionError: Lists differ: [\'-1\'] != [12]\n\nFirst differing element 0:\n\'-1\'\n12\n\n- [\'-1\']\n+ [12]\n\n======================================================================\nFAIL: test59 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 366, in test59\n    self.assertEqual(patched_source(*input_59), original_source(*input_59))\nAssertionError: Lists differ: [\'-1\'] != [12]\n\nFirst differing element 0:\n\'-1\'\n12\n\n- [\'-1\']\n+ [12]\n\n======================================================================\nFAIL: test6 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 48, in test6\n    self.assertEqual(patched_source(*input_6), original_source(*input_6))\nAssertionError: Lists differ: [\'-1\'] != [12]\n\nFirst differing element 0:\n\'-1\'\n12\n\n- [\'-1\']\n+ [12]\n\n----------------------------------------------------------------------\nRan 100 tests in 0.007s\n\nFAILED (failures=4, errors=15)\n')