CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'...F.F.FFF\n======================================================================\nFAIL: test3 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 30, in test3\n    self.assertEqual(patched_source(input_3), original_source(input_3))\nAssertionError: Lists differ: [40] != [44]\n\nFirst differing element 0:\n40\n44\n\n- [40]\n?   ^\n\n+ [44]\n?   ^\n\n\n======================================================================\nFAIL: test5 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 42, in test5\n    self.assertEqual(patched_source(input_5), original_source(input_5))\nAssertionError: Lists differ: [28] != [32]\n\nFirst differing element 0:\n28\n32\n\n- [28]\n?   -\n\n+ [32]\n?  +\n\n\n======================================================================\nFAIL: test7 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 54, in test7\n    self.assertEqual(patched_source(input_7), original_source(input_7))\nAssertionError: Lists differ: [32] != [40]\n\nFirst differing element 0:\n32\n40\n\n- [32]\n+ [40]\n\n======================================================================\nFAIL: test8 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 60, in test8\n    self.assertEqual(patched_source(input_8), original_source(input_8))\nAssertionError: Lists differ: [28] != [32]\n\nFirst differing element 0:\n28\n32\n\n- [28]\n?   -\n\n+ [32]\n?  +\n\n\n======================================================================\nFAIL: test9 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 66, in test9\n    self.assertEqual(patched_source(input_9), original_source(input_9))\nAssertionError: Lists differ: [28] != [24]\n\nFirst differing element 0:\n28\n24\n\n- [28]\n?   ^\n\n+ [24]\n?   ^\n\n\n----------------------------------------------------------------------\nRan 10 tests in 0.003s\n\nFAILED (failures=5)\n')