CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'....................E....F..E........F....................\n======================================================================\nERROR: test27 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 174, in test27\n    self.assertEqual(patched_source(input_27), original_source(input_27))\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_acc_qb.py", line 4, in patched_func\n    (a, b) = [int(x) for x in args[0].split()]\nValueError: too many values to unpack (expected 2)\n\n======================================================================\nERROR: test34 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 216, in test34\n    self.assertEqual(patched_source(input_34), original_source(input_34))\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_acc_qb.py", line 4, in patched_func\n    (a, b) = [int(x) for x in args[0].split()]\nValueError: too many values to unpack (expected 2)\n\n======================================================================\nFAIL: test31 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 198, in test31\n    self.assertEqual(patched_source(input_31), original_source(input_31))\nAssertionError: Lists differ: [0] != [1]\n\nFirst differing element 0:\n0\n1\n\n- [0]\n+ [1]\n\n======================================================================\nFAIL: test42 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 264, in test42\n    self.assertEqual(patched_source(input_42), original_source(input_42))\nAssertionError: Lists differ: [0] != [1]\n\nFirst differing element 0:\n0\n1\n\n- [0]\n+ [1]\n\n----------------------------------------------------------------------\nRan 58 tests in 0.004s\n\nFAILED (failures=2, errors=2)\n')