# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import src_1341 as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    module_0.func()


def test_case_1():
    str_0 = "6|"
    list_0 = [str_0, str_0]
    var_0 = module_0.func(*list_0)


def test_case_2():
    str_0 = "00{"
    list_0 = [str_0, str_0]
    var_0 = module_0.func(*list_0)


def test_case_3():
    str_0 = "7|"
    list_0 = [str_0, str_0]
    var_0 = module_0.func(*list_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "1 b"
    list_0 = [str_0, str_0]
    var_0 = module_0.func(*list_0)
    object_0 = module_1.object()
    var_1 = module_1.object()
    module_0.func(*var_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = "1f"
    list_0 = [str_0, str_0]
    var_0 = module_0.func(*list_0)
    module_1.object(*list_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    str_0 = "1c"
    list_0 = [str_0, str_0]
    var_0 = module_0.func(*list_0)
    module_0.func(*var_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    str_0 = "52d"
    list_0 = [str_0, str_0, str_0, str_0, str_0, str_0]
    var_0 = module_0.func(*list_0)
    module_0.func()


@pytest.mark.xfail(strict=True)
def test_case_8():
    str_0 = "5\re"
    list_0 = [str_0, str_0, str_0, str_0]
    var_0 = module_0.func(*list_0)
    module_0.func()


@pytest.mark.xfail(strict=True)
def test_case_9():
    str_0 = "1 a"
    list_0 = [str_0, str_0]
    var_0 = module_0.func(*list_0)
    module_0.func()
