CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'FF.F.FFFFF\n======================================================================\nFAIL: test0 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 12, in test0\n    self.assertEqual(patched_source(input_0), original_source(input_0))\nAssertionError: Lists differ: [7] != [3]\n\nFirst differing element 0:\n7\n3\n\n- [7]\n+ [3]\n\n======================================================================\nFAIL: test1 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 18, in test1\n    self.assertEqual(patched_source(input_1), original_source(input_1))\nAssertionError: Lists differ: [5] != [2]\n\nFirst differing element 0:\n5\n2\n\n- [5]\n+ [2]\n\n======================================================================\nFAIL: test3 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 30, in test3\n    self.assertEqual(patched_source(input_3), original_source(input_3))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test5 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 42, in test5\n    self.assertEqual(patched_source(input_5), original_source(input_5))\nAssertionError: Lists differ: [5] != [2]\n\nFirst differing element 0:\n5\n2\n\n- [5]\n+ [2]\n\n======================================================================\nFAIL: test6 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 48, in test6\n    self.assertEqual(patched_source(input_6), original_source(input_6))\nAssertionError: Lists differ: [6] != [2]\n\nFirst differing element 0:\n6\n2\n\n- [6]\n+ [2]\n\n======================================================================\nFAIL: test7 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 54, in test7\n    self.assertEqual(patched_source(input_7), original_source(input_7))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test8 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 60, in test8\n    self.assertEqual(patched_source(input_8), original_source(input_8))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test9 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 66, in test9\n    self.assertEqual(patched_source(input_9), original_source(input_9))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n----------------------------------------------------------------------\nRan 10 tests in 0.002s\n\nFAILED (failures=8)\n')