
 NEW TEST OUTPUT: 
CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'E\n======================================================================\nERROR: test0 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 12, in test0\n    self.assertEqual(patched_source(input_0), original_source(input_0))\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_bug_qb.py", line 9, in original_func\n    global_list.append(i, p)\nTypeError: list.append() takes exactly one argument (2 given)\n\n----------------------------------------------------------------------\nRan 1 test in 0.000s\n\nFAILED (errors=1)\n')
 NEW TEST OUTPUT: 
CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'F\n======================================================================\nFAIL: test0 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 12, in test0\n    self.assertEqual(patched_source(input_0), original_source(input_0))\nAssertionError: Lists differ: [1] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n1\n\n- [1]\n?  -\n\n+ []\n\n----------------------------------------------------------------------\nRan 1 test in 0.001s\n\nFAILED (failures=1)\n')