============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.4.0
rootdir: /home/khashayar/projs/det-gen
plugins: anyio-4.3.0
collected 1 item

c4b_bak/src_786/9/test_transformed_src_786.py F                          [100%]

=================================== FAILURES ===================================
_________________________________ test_case_0 __________________________________

    def test_case_0():
        float_0 = -2254.9
        object_0 = module_0.object()
        list_0 = [float_0, object_0]
        var_0 = module_1.func(*list_0)
>       assert (
            var_0
            == "33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 11 10 9 6 5 2 "
        )
E       AssertionError: assert '333231302928...5141311109652' == '33 32 31 30 ...1 10 9 6 5 2 '
E         - 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 11 10 9 6 5 2 
E         ?   -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  - - - - -
E         + 33323130292827262524232221201918171615141311109652

c4b_bak/src_786/9/test_transformed_src_786.py:13: AssertionError
=============================== warnings summary ===============================
c4b_bak/src_786/9/src_786.py:6
  /home/khashayar/projs/det-gen/c4b_bak/src_786/9/src_786.py:6: SyntaxWarning: "is not" with a literal. Did you mean "!="?
    if ((n & (1 << i)) is not 0):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED c4b_bak/src_786/9/test_transformed_src_786.py::test_case_0 - Assertion...
========================= 1 failed, 1 warning in 0.03s =========================
